name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Trigger hanya saat ada push ke branch main
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Load environment variables
        run: echo "${{ secrets.ENV_VARS }}" > .env

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/foto-studio:latest .
          
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/foto-studio:latest
